apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dev-app-deploy
  title: Deploy an Application from Source Code Repository
  description: Deploy Custom Resources from a Repository
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - repoURL
      properties:
        repoURL:
          title: Target repo SSH Clone URL
          type: string
          description: The SSH Clone URL of the repo containing your Custom Resources
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Developer Name
      required:
        - developerName
      properties:
        developerName:
          title: Developer Name
          type: string
          description: The developer name to associate resources with
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a Target Cloud Environment
      required:
        - targetEnv
      properties:
        targetEnv:
          title: Target Environment
          type: string
          enum: ["IBM Cloud", "AWS", "Azure", "GCP"]
    - title: Name your deployed application
      required:
        - applicationName
      properties:
        applicationName:
          title: Application Name
          type: string
          description: Unique name of your application
          ui:autofocus: true
          ui:options:
            rows: 5
  steps:
    - id: trigger_build
      name: Trigger Build Pipeline
      action: ibm:call-cr-pipeline
      input:
        repoURL:  ${{ parameters.repoURL }}
        developerName:  ${{ parameters.developerName }}
        targetEnv: ${{ parameters.targetEnv }}
        applicationName: ${{ parameters.applicationName }}

