apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: components
  description: A collection of all components
spec:
  targets:
    - ./components/deployed-clusters.yaml
    - ./components/developer-repo.yaml
    - ./components/managed-clusters.yaml
    - ./components/ace-servers.yaml
    - ./components/mq-servers.yaml
    - ./components/ace-server-test.yaml
    - ./components/mq-server-test.yaml
    - ./components/redis-resource.yaml
    - ./components/guestbook-component.yaml
    - ./components/redis-component.yaml
    - ./components/app-component.yaml
