apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: govtech 
  title: govtech-managed-cluster 
  description: Managed AWS cluster 
spec:
  type: kubernetes-cluster
  lifecycle: experimental
  owner: group:ce-apac
  cloud: aws
