apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
#     'backstage.io/kubernetes-id': test-app
    'backstage.io/kubernetes-label-selector': 'appconnect.ibm.com/kind=IntegrationServer,backstage.io/kubernetes-id=test-app'
    tektonci/build-namespace: backstage
    tektonci/pipeline-label-selector: 'build-name=developer-app-deploy'
  name: developer-repo
  description: Developer repo Catalog
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: guest-system
