apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    'backstage.io/kubernetes-id': test-app
    tektonci/build-namespace: tekton
    tektonci/pipeline-label-selector: 'build-name=mq-resource-submission'
  name: mq-servers
  description: Deployed MQ Servers
spec:
  type: service
  lifecycle: production
  owner: user:guest