apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cluster-deploy-template
  title: Deploy a Kubernetes Cluster
  description: Deploy a Kubernetes Cluster using the IBM OTP Pattern
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Choose a Target Cloud Environment
      required:
        - targetEnv
      properties:
        targetEnv:
          title: Target Cloud Environment
          type: string
          enum: ["IBM Cloud", "AWS", "Azure", "GCP"]
    - title: Choose a Location
      required:
        - location
      properties:
        location:
          title: Cluster Location
          type: string
          enum: ["Suprise Me!", "apac", "north-america", "south-america", "emea"]
    - title: Choose a Cluster Size
      required:
        - size
      properties:
        size:
          title: Cluster Size
          type: string
          enum: ["small", "medium", "large"]
    - title: Name your Cluster
      required:
        - name
      properties:
        name:
          title: Cluster Name
          type: string
          description: Unique name of your deployment
          ui:autofocus: true
          ui:options:
            rows: 5
  steps:
    - id: trigger_build
      name: Trigger Build Pipeline
      action: ibm:call-build-pipeline
      input:
        targetEnv:  "AWS"
        deploymentName:  ${{ parameters.name }}
